version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "website-alerter"
resolve_s3 = true
s3_prefix = "website-alerter"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = 'EnvType="prod"'
